version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      RAILS_ROLE: web
      # Chromium/Puppeteer settings
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
      PUPPETEER_SKIP_DOWNLOAD: "true"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle   # persists gems
      - sqlite_data:/app/db
      - storage:/app/storage
    depends_on:
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      # Chromium/Puppeteer settings
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
      PUPPETEER_SKIP_DOWNLOAD: "true"
      RAILS_ROLE: worker
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - sqlite_data:/app/db
      - storage:/app/storage
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data

volumes:
  bundle:
  sqlite_data:
  storage:
  redisdata:
